var expect = require('expect.js');
var sinon = require('sinon');
var mixins = require('..');

describe('mixin into objects', function(){
    describe('basic functionality', function(){
        var klass, klassFunctionCalled, bothValue;
        beforeEach(function(){
           // <generated by 6to5 on Mon Feb 2 2015 (UTC)>
               "use strict";

                var _inherits = function (subClass, superClass) { if (typeof superClass !== "function" && superClass !== null) { throw new TypeError("Super expression must either be null or a function, not " + typeof superClass); } subClass.prototype = Object.create(superClass && superClass.prototype, { constructor: { value: subClass, enumerable: false, writable: true, configurable: true } }); if (superClass) subClass.__proto__ = superClass; };

                var _prototypeProperties = function (child, staticProps, instanceProps) { if (staticProps) Object.defineProperties(child, staticProps); if (instanceProps) Object.defineProperties(child.prototype, instanceProps); };

                var BaseKlass = (function () {
                  function BaseKlass() {}

                  _prototypeProperties(BaseKlass, null, {
                    add: {
                      value: function add(x, y) {
                        return x + y;
                      },
                      writable: true,
                      configurable: true
                    }
                 });

                  return BaseKlass;
                })();
 
                var Klass = (function (BaseKlass) {
                  function Klass() {
                    if (Object.getPrototypeOf(Klass) !== null) {
                      Object.getPrototypeOf(Klass).apply(this, arguments);
                    }
                  }

                  _inherits(Klass, BaseKlass);

                  _prototypeProperties(Klass, null, {
                    setsCalled: {
                      value: function setsCalled() {
                        klassFunctionCalled = true;
                      },
                      writable: true,
                      configurable: true
                    },
                    both: {
                      value: function both() {
                        bothValue++;
                      },
                      writable: true,
                      configurable: true
                    }
 
                  });

                  return Klass;
                })(BaseKlass);
            // </ generated by 6to5 on Mon Feb 2 2015 (UTC) >
            klass = Klass;
            klassFunctionCalled = false;
            bothValue = 0;
        });

        var mixin = mixins({
            both: mixins.MANY
        });

        it('is sane', function(){
            mixin(klass, {});
            expect(new klass().add(3, 4)).to.be(7);
        });

        it('handles MANY correctly', function(){
            new klass().both();
            expect(bothValue).to.be(1);
            mixin(klass.prototype, {
                both: function(){ bothValue += 10 }
            });
            new klass().both();
            expect(bothValue).to.be(1+1+10);
        });

        it('returns the mixer result', function(){
            mixins({
                add: function(left, right){
                    return function(){ return 'sentinial' }
                }
            })(klass.prototype, {add: function(){}});
            expect(new klass().add()).to.be('sentinial');
        });

        it('allows mixer to return arbitrary values', function(){
            mixins({
                add: function(left, right){
                    return left.length + ' sentinial'
                }
            })(klass.prototype, {add: function(){}});
            expect(new klass().add).to.be('2 sentinial');
        });

        it('defaults to ONCE', function(){
            expect(function(){
                mixin(klass.prototype, {add: function(){}});
            }).to.throwException();
        });
    });

    describe('opts', function(){
        var klass;
        beforeEach(function(){
            function Klass(){};
            Klass.prototype.foo = function(){ return 'foo'; };
            Klass.prototype.bar = 'string bar';
            klass = Klass;
        });

        it('allows overriding unknownFunction', function(){
            function add(x, y){ return function(){ return x() + y() } };
            mixins({}, {unknownFunction: add})(klass.prototype, {foo: function(){ return 'baz' }});
            expect(new klass().foo()).to.be('foobaz');
        });

        it('calls nonFunctionProperty', function(){
            mixins({}, {
                nonFunctionProperty: function(a, b, key){ 
                    expect(a).to.be('string bar');
                    expect(b).to.be('sentinial');
                    expect(key).to.be('bar');
                    return 7;
                }
            })(klass.prototype, {bar: 'sentinial'});
            expect(klass.prototype.bar).to.be(7);
        });

        it('calls nonFunctionProperty when one is a function', function(){
            var fn = function(){};
            mixins({}, {
                nonFunctionProperty: function(a, b, key){ 
                    expect(a).to.be('string bar');
                    expect(b).to.be(fn);
                    expect(key).to.be('bar');
                    return 7;
                }
            })(klass.prototype, {bar: fn});
            expect(klass.prototype.bar).to.be(7);
        });
    });
});
